### ISSUE TITLE
Deserializing webhook notification to ChangeNotificationCollection throws exception

### ISSUE THREAD

**Issue by akudhingra** [microsoftgraph/msgraph-beta-sdk-dotnet#107]
I'm using the following code to deserialize a webhook notification to Microsoft.Graph.ChangeNotificationCollection from version 0.18.0-preview of the Graph Beta package:

`var notifications = JsonConvert.DeserializeObject<ChangeNotificationCollection>(content);`

where content contains the notification json received from Microsoft, which looks like the following:

```
{
	"value": [
		{
			"subscriptionId": "xxxx-xxxx-xxxx-xxxx",
			"changeType": "created",
			"tenantId": "xxxx-xxxx-xxxx-xxxx",
			"clientState": "xxxxxxxx",
			"subscriptionExpirationDateTime": "2020-05-05T19:42:22.9367027+00:00",
			"resource": "teams('xxxx-xxxx-xxxx-xxxx')/channels('xxxx-xxxx-xxxx-xxxx')/messages('12345')/replies('12345')",
			"resourceData": {
				"id": "12345",
				"@odata.type": "#Microsoft.Graph.ChatMessage",
				"@odata.id": "teams('xxxx-xxxx-xxxx-xxxx')/channels('19:e445@thread.skype')/messages('12345')/replies('12345')"
			},
			"encryptedContent": {
				"data": "ZRdtYfzkkQCjzic3PJ/RHJisQ7Rwpi5qyob",
				"dataSignature": "Sm98cL41M9rX+sVreb6pnsAFgU",
				"dataKey": "XBiuWobA05",
				"encryptionCertificateId": "certId_xyz",
				"encryptionCertificateThumbprint": "6E108"
			}
		}
	],
	"validationTokens": [
		"eyJ0eXAiOi"
	]
```

But this fails with the following exception:

```
System.InvalidCastException Unable to cast object of type 'Microsoft.Graph.ChatMessage' to type 'Microsoft.Graph.ResourceData'. Void SetResourceData(System.Object, System.Object)    at SetResourceData(Object , Object )
   at Newtonsoft.Json.Serialization.DynamicValueProvider.SetValue(Object target, Object value)

```

```
Newtonsoft.Json.JsonSerializationException Error setting value to 'ResourceData' on 'Microsoft.Graph.ChangeNotification'. Void SetValue(System.Object, System.Object)    at Newtonsoft.Json.Serialization.DynamicValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Microsoft.Graph.DerivedTypeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Microsoft.Graph.DerivedTypeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)

``` 
[AB#7171](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7171)

**Comment by MIchaelMainer** [comment]
We have some work to do to properly support this. This will be supported in the 2.0 release of our core library.

cc: @baywet

**Comment by MIchaelMainer** [comment]
https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/104

**Comment by baywet** [comment]
@akudhingra there's a workaround you can use in the meantime with system.text.json. see the sample here https://www.github.com/microsoftgraph/aspnetcore-webhooks-sample/tree/master/src%2FGraphWebhooks-Core%2FControllers%2FNotificationController.cs

**Comment by baywet** [comment]
The work we're doing currently is to enable validation and decryption of the encrypted content right from the SDK

**Comment by vadrsa** [comment]
@baywet When using the workaround you mentioned, the Microsoft.Graph.ResourceData's AdditionalData is always null since JsonExtensionData only works with Newtonsoft.Json Serializers.

Another workaround would be adding the following custom contract resolver
```cs
class IgnoreDerivedTypeContractResolver : DefaultContractResolver
	{

        protected override JsonConverter ResolveContractConverter(Type objectType)
        {
            var converter = base.ResolveContractConverter(objectType);
            if (typeof(DerivedTypeConverter).Equals(converter?.GetType()))
            {
                return null;
            }
            return converter;
        }
    }
```
And deserializing like this
```cs
var serializerSetting = new JsonSerializerSettings()
{
	ContractResolver = new IgnoreDerivedTypeContractResolver()
};
ChangeNotificationCollection notificationCollection = JsonConvert.DeserializeObject<ChangeNotificationCollection>(requestBody, serializerSetting);
```

Although I don't understand why would ChangeNotification's ResourceData property be of type ResourceData but the types that 
are going to be deserialized into it be inherited from class Entity(like 'Microsoft.Graph.ChatMessage').

**Comment by baywet** [comment]
Thanks for the additional information. That's because the resourceData only contains metadata + the encrypted data. It does not contain an actual representation of the object and needs to be decrypted/validated before being able to access the information. On top of that, this property is generic (i.e. if you subscribe to chat messages, you'll get a encrypted chat message object in there, if you subscribe to presence information, you'll get an encrypted user presence information object in there)

**Comment by andrueastman** [comment]
This is resolved via microsoftgraph/msgraph-sdk-dotnet-core#256 and should now be available through https://www.nuget.org/packages/Microsoft.Graph.Beta/4.4.0-preview

**Comment by baywet** [comment]
@andrueastman 
I had started the work to include extra functionality for rich notifications (serialization of the certificate, validation & decryption of payload) in the dotnet SDK back when I was a PM for the feature. Would you mind taking over my old PRs, rebasing and merging the work so it's part of the upcoming release?

https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/754
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/117
https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/104

**Comment by andrueastman** [comment]
Sure thing @baywet! I will take a look and action on them,
