### ISSUE TITLE
Error on RevokeSignInSessions (and InvalidateAllRefreshTokens)

### ISSUE THREAD

**Issue by zekieshevked** [microsoftgraph/msgraph-beta-sdk-dotnet#150]
Not sure if this is an issue in Graph but it would be great if you could give some directions where to search for the problem. Thanks.

The following error occurs when RevokeSignInSessions request is sent (the same error occurs for InvalidateAllRefreshTokens request too) in one of the our projects:

---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadAsBoolean()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.Graph.Serializer.DeserializeObject[T](String inputString)
   at Microsoft.Graph.ResponseHandler.HandleResponse[T](HttpResponseMessage response)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)

The other requests work fine - GetAsync, AddAsync, UpdateAsync, DeleteAsync.

**Comment by zekieshevked** [comment]
Could this be related to the following known issue from the documentation [Revoke sign-in sessions returns wrong HTTP code](https://docs.microsoft.com/en-us/graph/known-issues#revoke-sign-in-sessions-returns-wrong-http-code) ?

**Comment by MIchaelMainer** [comment]
This is likely caused by that issue and our client is not expecting to see the boolean value in the response. You'll need to keep an eye out for the resolution of that known issue.
