### ISSUE TITLE
Exception deserializing GroupMembers when called from V1.0 library followed by the Beta library

### ISSUE THREAD

**Issue by akudhingra** [microsoftgraph/msgraph-beta-sdk-dotnet#163]
## Exception
System.ArgumentException: The value 'Microsoft.Graph.User' is not of type 'Microsoft.Graph.DirectoryObject' and cannot be used in this generic collection.

## Steps to Reproduce

1. Create a new C# console project using .NET framework
2. Add Nuget dependencies: 
  2.1. Microsoft.identity.Client vesion **4.19.0 (latest stable)**
  2.2. Microsoft.Graph verion **3.15.0 (latest stable)**
  2.3. Microsoft.Graph.Beta version **0.26.0 (latest prerelease)**
3. Follow the steps from the github home page of this repo to use the two libraries together: https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet#using-the-beta-client-along-with-the-v10-library
4. Write code to get a group's members using the V1.0 library:
```
private static async Task PrintGroupMembersFromV1_0(string groupId)
{
	var client = await ServiceClientFactory.CreateV1_0GraphServiceClient();

	try
	{
		Console.WriteLine("Group Members from the V1.0 endpoint ");

		IGroupMembersCollectionWithReferencesPage members = await client
			.Groups[groupId]
			.Members
			.Request()
			.GetAsync();

		foreach (var member in members)
			Console.WriteLine($"Member: {member.ODataType}, {member.Id}");
	}
	catch (Exception ex)
	{
		Console.WriteLine(ex);
	}
}
```
4. Write code to get a group's members using the Beta library this time:
```
private static async Task PrintGroupMembersFromBeta(string groupId)
{
	var client = await ServiceClientFactory.CreateBetaGraphServiceClient();

	try
	{
		Console.WriteLine("Group Members from the beta endpoint ");

		GraphBeta.IGroupMembersCollectionWithReferencesPage members = await client
			.Groups[groupId]
			.Members
			.Request()
			.GetAsync();

		foreach (var member in members)
			Console.WriteLine($"Member: {member.ODataType}, {member.Id}");
	}
	catch (Exception ex)
	{
		Console.WriteLine(ex);
	}
}
```

6. Call the V1.0 method to get a group's members, followed by a call to the Beta method to get the group's members:
```
public static async Task Main(string[] args)
{
	const string GroupId = "00441fa6-471e-4318-9ec6-3b3e554056e3";

	await PrintGroupMembersFromV1_0(GroupId);
	await PrintGroupMembersFromBeta(GroupId);

	Console.ReadLine();
}
```
7. Calling the second method throws an exception when deserializing:
```
System.ArgumentException: The value 'Microsoft.Graph.User' is not of type 'Microsoft.Graph.DirectoryObject' and cannot be used in this generic collection.
Parameter name: value
   at Newtonsoft.Json.Utilities.CollectionWrapper`1.VerifyValueType(Object value)
   at Newtonsoft.Json.Utilities.CollectionWrapper`1.System.Collections.IList.Add(Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Converters.CustomCreationConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.Graph.Serializer.DeserializeObject[T](String inputString)
   at Microsoft.Graph.ResponseHandler.<HandleResponse>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.GroupMembersCollectionWithReferencesRequest.<GetAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GraphUserTest.Program.<PrintGroupMembersFromBeta>d__2.MoveNext() in <truncated>
```

## Analysis
The /group/id/members JSON response that is received from Graph is a list of directory objects. I see that when deserializing in Newtonsoft, the JsonConverter selected for deserializing each item of the list is Microsoft.Graph.DerivedTypeConverter from the Graph.Core library. 

This library seems to cache the Type to serialize to:
```
namespace Microsoft.Graph
{
  /// <summary>
  /// Handles resolving interfaces to the correct derived class during serialization/deserialization.
  /// </summary>
  public class DerivedTypeConverter : JsonConverter
  {
    internal static readonly ConcurrentDictionary<string, Type> TypeMappingCache = 
        new ConcurrentDictionary<string, Type>((IEqualityComparer<string>) StringComparer.OrdinalIgnoreCase);
```

Here is what I think is happening and is the root cause of the bug:

When we make the first call to GetGroupMembers using the v1.0 endpoint, items (members) with oDataType "#microsoft.graph.user" get mapped to Microsoft.Graph.User type from the v1.0 library, and the DerivedTypeConverter caches this mapping. These users are then added to a list of base type DirectoryObject from the same library, it's all good!

When we make the second call to get the group members again, but this time from the beta library, the individual items are deserialized to the cached type User from the v1.0 library, but an attempt to add this object from v1.0 to a list of DirectoryObjects from the beta library, an exception is thrown.

I've attached a sample project that demonstrates this. 

[GraphUserTest1.zip](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/files/5320571/GraphUserTest1.zip)

You'll need to update the following constants to make it work with your tenancy:
* Program.cs
  * GroupId
* ServiceClientFactory.cs
  * AppId
  * TenantId
  * CertificateSubject 
[AB#6326](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6326)

**Comment by MIchaelMainer** [comment]
We really need a beta namespace for our beta models.

**Comment by akudhingra** [comment]
@MIchaelMainer , is there a temporary workaround we could use in the meantime?

**Comment by MIchaelMainer** [comment]
@akudhingra First off, I want to thank you for a very thorough breakdown of the problem. I missed this in my first response, and I want you to know that your time and effort is appreciated. 

We didn't expect this scenario where the same type in beta and v1.0 would be used in the same project. Can you help me understand why you make the same call in v1.0 and beta? There is much risk that any beta API will have a breaking change underneath your code. 

Regarding a workaround, since the cache is a static concurrentdictionary, you'd need to run the v1.0 code and beta code in separate [app domains](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/application-domains). 

We really need to get the beta models into a different namespace.

**Comment by mairissi** [comment]
Closing this since we are going to track the progress through this [issue](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/139).
