### ISSUE TITLE
Missing GetDownloadUrl method for CaseExportOperation

### ISSUE THREAD

**Issue by oliveira-alexdias** [microsoftgraph/msgraph-beta-sdk-dotnet#338]
The [Microsoft Documentation](https://docs.microsoft.com/en-us/graph/api/ediscovery-caseexportoperation-getdownloadurl?view=graph-rest-beta&tabs=csharp) indicates to use the GetDownloadUrl like this:

```
var @string = await graphClient
	.Compliance
	.Ediscovery
	.Cases["{ediscovery.case-id}"]
	.Operations["{ediscovery.caseOperation-id}"]
	.GetDownloadUrl()
	.Request()
	.GetAsync();
```
However, the GetDownloadUrl is not available.

![error](https://user-images.githubusercontent.com/78912689/130850952-47504ebd-e51e-4a61-848f-3f0684fed1d5.jpg)
 
[AB#10865](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10865)

**Expected behavior**
It's expected to have GetDownloadUrl method

**Client version**
Microsoft.Graph version 4.9.0-preview

**Comment by oliveira-alexdias** [comment]
Hey @maisarissi I believe there is an issue in Download URL functionality. Either getting the Download URL throught this workaround you gave me or getting the Download URL throught HTTP call it is returning a 500 Internal Server Error.

Could you please check it?

- **Using the workaround**
```csharp
var client = await graph.GetROPCClient(Scopes.Default);

var requestUrl = client
               .Compliance
               .Ediscovery
               .Cases[aedCaseId.ToString()]
               .Operations[aedExportId]
               .AppendSegmentToRequestUrl("microsoft.graph.ediscovery.caseExportOperation/getDownloadUrl");

var request = new BaseRequest(requestUrl, client);
var response = await request.SendAsync<ODataMethodStringResponse>(null, CancellationToken.None);
return response.Value;
```

- _Message:_
Code: InternalServerError
Message: An unexpected error occurred.
Inner error:
	AdditionalData:
	date: 2021-12-14T18:35:56
	request-id: f79c42c4-d465-4624-9c37-d4bc19cd910c
	client-request-id: f79c42c4-d465-4624-9c37-d4bc19cd910c
ClientRequestId: f79c42c4-d465-4624-9c37-d4bc19cd910c

- _e.StackTrace:_
   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__40.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Skipjack.Exports.Services.Skipjack.<GetDownloadUriForBrowserDownload>d__27.MoveNext() in .\Functions\Exports\Services\GetDownloadUrl.cs:line 52

- **Using HTTP Call**
![image](https://user-images.githubusercontent.com/78912689/146062968-831e06c3-c084-4cea-9e74-a698d364f701.png)

**Comment by maisarissi** [comment]
@mahage-msft can you take a look at this? Since the error is also happening in the Graph Explorer doesn't sound like an SDK error.

**Comment by maisarissi** [comment]
Hi @oliveira-alexdias .
Are you still getting 500 using the workaround provided above?

**Comment by oliveira-alexdias** [comment]
Hey @maisarissi! Now it is working as expected. Thank you.

**Comment by maisarissi** [comment]
Closing it as resolved.

**Comment by maisarissi** [comment]
Great to hear @oliveira-alexdias .

I'll keep this open to track the OData cast fix. Thank you!

**Comment by andrueastman** [comment]
This is currently not showing up on the OpenAPI reference metadata due to the conversion library limiting child paths on derived/odata cast paths. Currently tracked via https://github.com/microsoft/OpenAPI.NET.OData/issues
