### ISSUE TITLE
Internal server error using MSGraph delta query for application endpoint

### ISSUE THREAD

**Issue by tucane** [microsoftgraph/msgraph-beta-sdk-dotnet#34]
I am getting an internal server error when calling the application beta sdk endpoint after getting a few pages with. `graphServiceClient.Applications.Delta().Request();
`

The few pages always work, but after that it's consistently failing.

This is the error message: 
```
Microsoft.Graph.ServiceException
  HResult=0x80131500
  Message=Code: InternalServerError
Message: Error while processing response.
Inner error:
	AdditionalData:
	request-id: 959d7917-5576-49e6-a734-524d2b6e94f8
	date: 10/16/2019 5:31:03 PM
ClientRequestId: 959d7917-5576-49e6-a734-524d2b6e94f8

  Source=Microsoft.Graph.Core
  StackTrace:
   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__35.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendAsync>d__31`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.ApplicationDeltaRequest.<GetAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AADPermissionIngest.Program.Main(String[] args) in C:\Source\Repos\SR-DT-DPlat-BigData\ISRMDataPlatform\Misc\AADPermissionIngest\AADPermissionIngest\Program.cs:line 106
```

**Comment by MIchaelMainer** [comment]
Can you try this with the v1.0 endpoint as this API is now generally available? How are you paging through the results?

**Comment by tucane** [comment]
@MIchaelMainer Does not work with v1.0 either. I've been working with the MSGraph team internally, and it seems like it's a problem with a misconfigured app in the Microsoft domain.

**Comment by ankurpiparsania** [comment]
@tucane, did you manage to find solution for above issue? What was misconfigured in app?

**Comment by tucane** [comment]
@ankurpiparsania I ended up using the non-delta endpoint for this as the error was blocking delivery and the customer was fine with pulling all data too. 
Not exactly sure what was misconfigured though. We've only tried removing the problematic app instead of fixing the configuration.

**Comment by ddyett** [comment]
closing as service bug we can't address.
