### ISSUE TITLE
Error getting the second page of eDiscovery.NoncustodialDataSources

### ISSUE THREAD

**Issue by rubens-farias** [microsoftgraph/msgraph-beta-sdk-dotnet#370]
Console application, .NET Core 3.1, Microsoft.Graph.Beta 4.19.0-preview

I'm trying to get a list of all non-custodial data sources for an eDiscovery case; as `.NoncustodialDataSources` implements `ICollectionPage<T>`, I'm using an extension method to navigate through all data pages:

```
var ncds = await ropcContext
    .Compliance
    .Ediscovery
    .Cases["dca610ca-b2d6-4437-88af-c07d13af4a74"]
    .NoncustodialDataSources
    .Request()
    .Expand(i => i.DataSource)
    .GetAsync();

foreach (var eDataLocation in await ncds.EnumerateAllAsync())
    Console.WriteLine(eDataLocation.DisplayName);

public static class Extensions
{
    public static async Task<List<T>> EnumerateAllAsync<T>(this Microsoft.Graph.ICollectionPage<T> paged)
    {
        var result = new List<T>();
        while (paged != null && paged.Count > 0)
        {
            result.AddRange(paged);
            var next = (dynamic)paged;
            if (next.NextPageRequest == null) break;
            paged = await next.NextPageRequest.GetAsync();
        }
        return result;
    }
}
```

This extension relies on the assumption that if we don't have a next data page, the `NextPageRequest` property will be blank. However, we're receiving this error:

```
Microsoft.Graph.ServiceException
  HResult=0x80131500
  Message=Message: The query specified in the URI is not valid. Query option 'SkipToken' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.
Inner error:
	Message: Query option 'SkipToken' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.
AdditionalData:
	date: 2021-11-08T15:52:29
	request-id: bdea60ca-073c-4a41-8fe8-90607b5579f6
	client-request-id: bdea60ca-073c-4a41-8fe8-90607b5579f6
ClientRequestId: bdea60ca-073c-4a41-8fe8-90607b5579f6

  Source=Microsoft.Graph.Core
  StackTrace:
   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__40.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.Ediscovery.CaseNoncustodialDataSourcesCollectionRequest.<GetAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at ConsoleApp3.Extensions.<EnumerateAllAsync>d__0`1.MoveNext() in C:\Users\Rubens\source\repos\ConsoleApp3\Program.cs:line 62
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp3.Program.<Main>d__0.MoveNext() in C:\Users\Rubens\source\repos\ConsoleApp3\Program.cs:line 30

  This exception was originally thrown at this call stack:
    [External Code]
    ConsoleApp3.Extensions.EnumerateAllAsync<T>(Microsoft.Graph.ICollectionPage<T>) in Program.cs
    [External Code]
    ConsoleApp3.Program.Main(string[]) in Program.cs
```

Inspecting the request using Fiddler, I can confirm the problem happens on the server side:

```
GET https://graph.microsoft.com/beta/compliance/ediscovery/cases/dca610ca-b2d6-4437-88af-c07d13af4a74/noncustodialDataSources?$expand=dataSource&$skiptoken=MyZRVkZCUVVGQlFVRXZMeTh2THk4dkx5OHZPRXRCUVVGQmNubEhUbk5SYlhFd2EyVTJlRE5IWTJ0WFlrRm1VVDA5 HTTP/1.1
Host: graph.microsoft.com
SdkVersion: Graph-dotnet-2.0.5
FeatureFlag: 0000004F
Cache-Control: no-store, no-cache
Authorization: Bearer eyJ0eXAiOiJ...
Accept-Encoding: gzip

HTTP/1.1 400 Bad Request
Date: Mon, 08 Nov 2021 15:52:28 GMT
Content-Type: application/json
Cache-Control: no-cache
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: bdea60ca-073c-4a41-8fe8-90607b5579f6
client-request-id: bdea60ca-073c-4a41-8fe8-90607b5579f6
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Brazil South","Slice":"E","Ring":"3","ScaleUnit":"001","RoleInstance":"CP1PEPF00002B25"}}
Content-Length: 535

{
   "error":{
      "code":"",
      "message":"The query specified in the URI is not valid. Query option 'SkipToken' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.",
      "innerError":{
         "message":"Query option 'SkipToken' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.",
         "date":"2021-11-08T15:52:29",
         "request-id":"bdea60ca-073c-4a41-8fe8-90607b5579f6",
         "client-request-id":"bdea60ca-073c-4a41-8fe8-90607b5579f6"
      }
   }
}
```

Looking at the [Compliance Center](https://compliance.microsoft.com/advancedediscovery/cases/v2/dca610ca-b2d6-4437-88af-c07d13af4a74?casesworkbench=DatasourcesTab), I can confirm that particular case has 12 NCDS:
![image](https://user-images.githubusercontent.com/2456804/140776817-4ae6c4d0-59fb-4480-b7c6-b9d9198d009d.png)

**Comment by andrueastman** [comment]
Thanks for raising this @rubens-farias,

@mahage-msft any chance you could confirm for us if this is a bug on the API endpoint?

**Comment by maisarissi** [comment]
Hi @mahage-msft .

Can you please take a look at this issue?

**Comment by SeunginLyu** [comment]
@maisarissi hi Maisa, I'll look into this, thank you

**Comment by SeunginLyu** [comment]
The engineering team tested this on the latest beta SDK (4.38) and the issue is fixed. @rubens-farias could you update the sdk to the latest version and try again?
