### ISSUE TITLE
Patch Security Incident - Exception of type 'Microsoft.Graph.Beta.Models.ODataErrors.ODataError' was thrown.

### ISSUE THREAD

**Issue by cammurray** [microsoftgraph/msgraph-beta-sdk-dotnet#531]
`        // Update incident tags
       addTags = new List<string>(){"Tag1","Tag2"};

        await _graphService.Security.Incidents[IncidentId]
                                    .PatchAsync(new Incident
                                    {
                                        Tags = addTags
                                    });
`

Stack: 

   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendNoContentAsync(RequestInformation requestInfo, IResponseHandler responseHandler, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendNoContentAsync(RequestInformation requestInfo, IResponseHandler responseHandler, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Beta.Security.Incidents.Item.IncidentItemRequestBuilder.PatchAsync(Incident body, Action`1 requestConfiguration, IResponseHandler responseHandler, CancellationToken cancellationToken)

**Comment by andrueastman** [comment]
Hey @cammurray,

Any chance you can still replicate this with the latest 5.14.0-preview version of the SDK?
