### ISSUE TITLE
Users AssignLicense PostAsync Microsoft.Graph.Beta.Models.ODataErrors.ODataError exception

### ISSUE THREAD

**Issue by cammurray** [microsoftgraph/msgraph-beta-sdk-dotnet#532]
SDK Version 5.10.0-preview

`
        string SkuId = "06ebc4ee-1bb5-47dd-8120-11324bc54e06";

        var LicenseRequest = new AssignLicensePostRequestBody
        {
            AddLicenses = new List<AssignedLicense>()
            {
                new AssignedLicense
                {
                    SkuId = LicenseSKU
                }
            }
        };

var licenseResponse = await graphClient.Users[UserResponse.Id].AssignLicense.PostAsync(LicenseRequest);

`

Exception of type 'Microsoft.Graph.Beta.Models.ODataErrors.ODataError' was thrown.

   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping)

   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, IResponseHandler responseHandler, Dictionary`2 errorMapping, CancellationToken cancellationToken)

   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, IResponseHandler responseHandler, Dictionary`2 errorMapping, CancellationToken cancellationToken)

   at Microsoft.Graph.Beta.Users.Item.AssignLicense.AssignLicenseRequestBuilder.PostAsync(AssignLicensePostRequestBody body, Action`1 requestConfiguration, IResponseHandler responseHandler, CancellationToken cancellationToken)

**Comment by cammurray** [comment]
@andrueastman is there anything that I can do here to assist? E.g any more troubleshooting that I can do? The exception that's provided out of Kiota is quite generic, so i'm not sure what's next.

**Comment by andrueastman** [comment]
Hey @cammurray,

Any chance you can try logging the given exception message as outlined here and share the results?

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#error-handling

**Comment by cammurray** [comment]
@andrueastman thanks, this helped a lot with the troubleshooting and exposes the error back from Graph, 

_"One or more parameters of the operation 'assignLicense' are missing from the request payload. The missing parameters are: removeLicenses."_

It turns out that the old graph client must be populating this mandatory param with a null list..

This works:

`
        var LicenseRequest = new AssignLicensePostRequestBody
        {
            AddLicenses = new List<AssignedLicense>()
            {
                new AssignedLicense
                {
                    DisabledPlans = new List<string>()
                    {
                    },
                    SkuId = LicenseSKU
                }
            },
            RemoveLicenses = new List<string>()
        };
       
`

**Comment by andrueastman** [comment]
We'll close this one for now. 

Version 5 of the SDK now uses the backing store which only sends the properties set in the object as documented in the link below. 
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#backing-store

As the API expects the `RemoveLicenses` the parameter should be set as desired.
