### ISSUE TITLE
Microsoft.Graph.ServiceException: Code: itemNotFound and  Code: NotFound

### ISSUE THREAD

**Issue by tgr989** [microsoftgraph/msgraph-beta-sdk-dotnet#58]
The Two exceptions offen occurs to me, Could you help me review the issues? thank you!

Azure Account: Developer Account
Graph API SDK: Microsoft.Graph.Beta 0.11.0-preview

My observations: the more frequently the APIs are called, the greater the probability is, especially Delete Member API.

Could you give me some suggestions.

```
        // Delete a sharing permission from a file or folder
        // https://docs.microsoft.com/zh-cn/graph/api/permission-delete?view=graph-rest-beta&tabs=http
        // Files.ReadWrite.All, Sites.ReadWrite.All(from least to most privileged)
        public static async Task DeleteSharingPermissionsAsync(string groupId, string itemId, string permId)
        {
            await graphClient.Groups[groupId].Drive.Items[itemId].Permissions[permId]
                .Request()
                .DeleteAsync()
                .ConfigureAwait(false);
        }
-----------------------------
Microsoft.Graph.ServiceException: Code: itemNotFound
Message: The resource could not be found.
Inner error:
    AdditionalData:
    request-id: 4cc7f3b3-288c-4833-ad25-0290996ca07c
    date: 2020-01-15T07:46:21
ClientRequestId: 4cc7f3b3-288c-4833-ad25-0290996ca07c

 

   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.PermissionRequest.DeleteAsync(CancellationToken cancellationToken)
```

```
    // Delete group member
    // https://docs.microsoft.com/zh-cn/graph/api/group-delete-members?view=graph-rest-beta&tabs=csharp
    // Application: GroupMember.ReadWrite.All, Group.ReadWrite.All, Directory.ReadWrite.All(from least to most privileged)
    public static async Task DeleteGroupUsersAsync(string groupId, string userId)
    {
      await graphClient
          .Groups[groupId]
          .Members[userId]
          .Reference
          .Request()
          .DeleteAsync()
          .ConfigureAwait(false);
    }
-------------------------
Status Code: NotFound
Microsoft.Graph.ServiceException: Code: Request_ResourceNotFound
Message: Resource '9c07bda6-0c22-463d-a152-e3c7592e28ca' does not exist or one of its queried reference-property objects are not present.
Inner error:
    AdditionalData:
    request-id: 66de6e08-553f-4620-bcce-9f0428164faf
    date: 2020-01-15T07:48:50
ClientRequestId: 66de6e08-553f-4620-bcce-9f0428164faf

 

   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.DirectoryObjectReferenceRequest.DeleteAsync(CancellationToken cancellationToken)
```

**Comment by darrelmiller** [comment]
Without knowing the set of Ids that you are trying to delete and without knowing if there are other users accessing this data it is difficult to know why items that you are trying to delete may already be deleted.  However, the end result is what you want, therefore the best approach may be simply to catch the exception and move on.
