### ISSUE TITLE
Microsoft.Graph.Beta.Models.ODataErrors.ODataError

### ISSUE THREAD

**Issue by tieje** [microsoftgraph/msgraph-beta-sdk-dotnet#627]
The query below results in the following error:

```csharp
var subscribedSkus = await Env.BetaGraphClient.SubscribedSkus
    .GetAsync(requestConfig =>{ requestConfig.QueryParameters.Select = new string[] { "id", "capabilityStatu", "skuPartNumber", "prepaidUnits", "consumedUnits" };
});
```

```
Microsoft.Graph.Beta.Models.ODataErrors.ODataError: Exception of type 'Microsoft.Graph.Beta.Models.ODataErrors.ODataError' was thrown.
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Beta.SubscribedSkus.SubscribedSkusRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
```

The problem is not with BetaGraphClient itself as it works for other queries. The app has all the permissions it needs.
I'm not sure how to solve this problem.
The original HTTP query that its based on works.
```
https://graph.microsoft.com/beta/subscribedSkus?$select=id,capabilityStatus,skuPartNumber,prepaidUnits,consumedUnits
```

**Comment by andrueastman** [comment]
Thanks for raising this @tieje 

Any chance you can look into the API error and confirm what you get when you follow the guidance on error handling at the link below?
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#error-handling

Also, it looks like the second property in the select array has a typo and should be `capabilityStatus` rather than `capabilityStatu`
