### ISSUE TITLE
DeviceManagement.DeviceConfigurations.PostAsync() doesn't work

### ISSUE THREAD

**Issue by jarrad-obrien** [microsoftgraph/msgraph-beta-sdk-dotnet#873]
### Describe the bug

Hi Team,

Nothing too crazy to describe. Using `DeviceManagement.DeviceConfigurations.PostAsync()` doesn't work. 

It throws `Exception: Microsoft.Graph.Beta.Models.ODataErrors.ODataError: Cannot create an abstract class`.

Using the same JSON and access token in a direct POST to `https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations` works.

The access token has permission `DeviceManagementConfiguration.ReadWrite.All`.

EDIT:

`DeviceManagement.GroupPolicyConfigurations.PostAsync()` and `DeviceManagement.DeviceManagementScripts.PostAsync()` work. These don't have derived types.

Whereas `DeviceManagement.DeviceConfigurations.PostAsync()` and `DeviceManagement.DeviceCompliancePolicies.PostAsync()` don't work. These have derived types.

It seems like classes with derived types are causing the issue.

### Expected behavior

A Device Configuration policy to be deployed in Intune.

It would be found at Intune > Devices > Manage Devices > Configuration (https://intune.microsoft.com/#view/Microsoft_Intune_DeviceSettings/DevicesMenu/~/configuration).

### How to reproduce

```
{
  "@odata.type": "#microsoft.graph.windows10CustomConfiguration",
  "roleScopeTagIds": [
    "0"
  ],
  "supportsScopeTags": false,
  "displayName": "Test POST to deviceManagement/deviceConfigurations",
  "omaSettings": [
    {
      "@odata.type": "#microsoft.graph.omaSettingString",
      "displayName": "Test OMA setting",
      "omaUri": "./Device/Vendor/MSFT/WindowsAdvancedThreatProtection/DeviceTagging/Group",
      "isEncrypted": false,
      "value": "TEST"
    }
  ]
}
```

    var jsonString = "{\n  \"@odata.type\": \"#microsoft.graph.windows10CustomConfiguration\",\n  \"roleScopeTagIds\": [\n    \"0\"\n  ],\n  \"supportsScopeTags\": false,\n  \"displayName\": \"Test POST to deviceManagement/deviceConfigurations\",\n  \"omaSettings\": [\n    {\n      \"@odata.type\": \"#microsoft.graph.omaSettingString\",\n      \"displayName\": \"Test OMA setting\",\n      \"omaUri\": \"./Device/Vendor/MSFT/WindowsAdvancedThreatProtection/DeviceTagging/Group\",\n      \"isEncrypted\": false,\n      \"value\": \"TEST\"\n    }\n  ]\n}";

    var deserializedPolicy = await KiotaJsonSerializer.DeserializeAsync(jsonString, DeviceConfiguration.CreateFromDiscriminatorValue);

    var pol = await graphClient.DeviceManagement.DeviceConfigurations.PostAsync(deserializedPolicy);

### SDK Version

5.78.0-preview

### Latest version known to work for scenario above?

N/A

### Known Workarounds

No workaround in C# besides a direct HTTP call to the API.

This PowerShell successfully uploads a policy. This is the same JSON as above:

```
$headerParams = @{
    Authorization = "Bearer $accessToken"
}

$jsonString = '{
    "@odata.type":  "#microsoft.graph.windows10CustomConfiguration",
    "roleScopeTagIds":  [
                            "0"
                        ],
    "supportsScopeTags":  false,
    "displayName":  "Test POST to deviceManagement/deviceConfigurations",
    "omaSettings":  [
        {
            "@odata.type":  "#microsoft.graph.omaSettingString",
            "displayName":  "Test OMA setting",
            "omaUri":  "./Device/Vendor/MSFT/WindowsAdvancedThreatProtection/DeviceTagging/Group",
            "isEncrypted":  false,
            "value":  "TEST"
        }
    ]
}'

$uri = "https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations"
$res = $null
$res = Invoke-RestMethod `
    -Uri $uri `
    -Method POST `
    -Headers $headerParams `
    -Body $json `
    -ContentType 'application/json'
```

### Debug output

<details><summary>Click to expand log</summary>
```

[2024-08-07T09:28:23.987Z] Function 'RestorePolicies', Invocation id '7b53e789-2732-4ce5-a6de-363df99ec973': An exception was thrown by the invocation.
[2024-08-07T09:28:23.990Z] Result: Function 'RestorePolicies', Invocation id '7b53e789-2732-4ce5-a6de-363df99ec973': An exception was thrown by the invocation.
Exception: Microsoft.Graph.Beta.Models.ODataErrors.ODataError: Cannot create an abstract class.
[2024-08-07T09:28:23.991Z]    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
[2024-08-07T09:28:23.991Z]    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
[2024-08-07T09:28:23.992Z]    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
[2024-08-07T09:28:23.993Z]    at Microsoft.Graph.Beta.DeviceManagement.DeviceConfigurations.DeviceConfigurationsRequestBuilder.PostAsync(DeviceConfiguration body, Action`1 requestConfiguration, CancellationToken cancellationToken)
[2024-08-07T09:28:23.994Z]    at FA.Platform.RestorePolicies.RestoreDeviceConfigs(String azureDevOpsAccessToken, GraphServiceClient graphClient, String azureDevOpsOrganization, String azureDevOpsProject, String azureDevOpsRepo, String azureDevOpsBranch) in C:\Users\Jarrad\source\repos\Frontend-MVP\FA.Platform\RestorePolicies.cs:line 357
[2024-08-07T09:28:23.995Z]    at FA.Platform.RestorePolicies.Restore(String shortCode, String tenantId, String clientId, String clientSecret) in C:\Users\Jarrad\source\repos\Frontend-MVP\FA.Platform\RestorePolicies.cs:line 70
[2024-08-07T09:28:23.995Z]    at FA.Platform.RestorePolicies.Run(HttpRequest req) in C:\Users\Jarrad\source\repos\Frontend-MVP\FA.Platform\RestorePolicies.cs:line 33
[2024-08-07T09:28:23.996Z]    at FA.Platform.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\Jarrad\source\repos\Frontend-MVP\FA.Platform\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 45
[2024-08-07T09:28:23.997Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-08-07T09:28:23.998Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 54
[2024-08-07T09:28:23.998Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89
Stack:    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
[2024-08-07T09:28:23.999Z]    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
[2024-08-07T09:28:24.000Z]    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
[2024-08-07T09:28:24.000Z]    at Microsoft.Graph.Beta.DeviceManagement.DeviceConfigurations.DeviceConfigurationsRequestBuilder.PostAsync(DeviceConfiguration body, Action`1 requestConfiguration, CancellationToken cancellationToken)
[2024-08-07T09:28:24.001Z]    at FA.Platform.RestorePolicies.RestoreDeviceConfigs(String azureDevOpsAccessToken, GraphServiceClient graphClient, String azureDevOpsOrganization, String azureDevOpsProject, String azureDevOpsRepo, String azureDevOpsBranch) in C:\Users\Jarrad\source\repos\Frontend-MVP\FA.Platform\RestorePolicies.cs:line 357
[2024-08-07T09:28:24.001Z]    at FA.Platform.RestorePolicies.Restore(String shortCode, String tenantId, String clientId, String clientSecret) in C:\Users\Jarrad\source\repos\Frontend-MVP\FA.Platform\RestorePolicies.cs:line 70
[2024-08-07T09:28:24.002Z]    at FA.Platform.RestorePolicies.Run(HttpRequest req) in C:\Users\Jarrad\source\repos\Frontend-MVP\FA.Platform\RestorePolicies.cs:line 33
[2024-08-07T09:28:24.002Z]    at FA.Platform.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\Jarrad\source\repos\Frontend-MVP\FA.Platform\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 45
[2024-08-07T09:28:24.003Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-08-07T09:28:24.003Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 54
[2024-08-07T09:28:24.004Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89.
[2024-08-07T09:28:24.137Z] Executed 'Functions.RestorePolicies' (Failed, Id=7b53e789-2732-4ce5-a6de-363df99ec973, Duration=14518ms)
[2024-08-07T09:28:24.140Z] System.Private.CoreLib: Exception while executing function: Functions.RestorePolicies. System.Private.CoreLib: Result: Failure
Exception: Microsoft.Graph.Beta.Models.ODataErrors.ODataError: Cannot create an abstract class.
[2024-08-07T09:28:24.141Z]    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
[2024-08-07T09:28:24.142Z]    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
[2024-08-07T09:28:24.143Z]    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
[2024-08-07T09:28:24.143Z]    at Microsoft.Graph.Beta.DeviceManagement.DeviceConfigurations.DeviceConfigurationsRequestBuilder.PostAsync(DeviceConfiguration body, Action`1 requestConfiguration, CancellationToken cancellationToken)
[2024-08-07T09:28:24.144Z]    at FA.Platform.RestorePolicies.RestoreDeviceConfigs(String azureDevOpsAccessToken, GraphServiceClient graphClient, String azureDevOpsOrganization, String azureDevOpsProject, String azureDevOpsRepo, String azureDevOpsBranch) in C:\Users\Jarrad\source\repos\Frontend-MVP\FA.Platform\RestorePolicies.cs:line 357
[2024-08-07T09:28:24.144Z]    at FA.Platform.RestorePolicies.Restore(String shortCode, String tenantId, String clientId, String clientSecret) in C:\Users\Jarrad\source\repos\Frontend-MVP\FA.Platform\RestorePolicies.cs:line 70
[2024-08-07T09:28:24.145Z]    at FA.Platform.RestorePolicies.Run(HttpRequest req) in C:\Users\Jarrad\source\repos\Frontend-MVP\FA.Platform\RestorePolicies.cs:line 33
[2024-08-07T09:28:24.145Z]    at FA.Platform.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\Jarrad\source\repos\Frontend-MVP\FA.Platform\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 45
[2024-08-07T09:28:24.146Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-08-07T09:28:24.147Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 54
[2024-08-07T09:28:24.149Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89
[2024-08-07T09:28:24.150Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
Stack:    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
[2024-08-07T09:28:24.151Z]    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
[2024-08-07T09:28:24.151Z]    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
[2024-08-07T09:28:24.152Z]    at Microsoft.Graph.Beta.DeviceManagement.DeviceConfigurations.DeviceConfigurationsRequestBuilder.PostAsync(DeviceConfiguration body, Action`1 requestConfiguration, CancellationToken cancellationToken)
[2024-08-07T09:28:24.154Z]    at FA.Platform.RestorePolicies.RestoreDeviceConfigs(String azureDevOpsAccessToken, GraphServiceClient graphClient, String azureDevOpsOrganization, String azureDevOpsProject, String azureDevOpsRepo, String azureDevOpsBranch) in C:\Users\Jarrad\source\repos\Frontend-MVP\FA.Platform\RestorePolicies.cs:line 357
[2024-08-07T09:28:24.155Z]    at FA.Platform.RestorePolicies.Restore(String shortCode, String tenantId, String clientId, String clientSecret) in C:\Users\Jarrad\source\repos\Frontend-MVP\FA.Platform\RestorePolicies.cs:line 70
[2024-08-07T09:28:24.156Z]    at FA.Platform.RestorePolicies.Run(HttpRequest req) in C:\Users\Jarrad\source\repos\Frontend-MVP\FA.Platform\RestorePolicies.cs:line 33
[2024-08-07T09:28:24.157Z]    at FA.Platform.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\Jarrad\source\repos\Frontend-MVP\FA.Platform\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 45
[2024-08-07T09:28:24.158Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-08-07T09:28:24.159Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 54
[2024-08-07T09:28:24.160Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89
[2024-08-07T09:28:24.161Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88.

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @jarrad-obrien 

Any chance you are able to share a code sample of the request when this fails when making a request with the C# sdk?
